name: YouTube Downloader

on:
  workflow_dispatch:
    inputs:
      youtube_urls:
        description: "YouTube URL"
        required: true
        type: string

      quality:
        description: "Video Quality"
        required: false
        default: "best"
        type: string

      download_subtitles:
        description: "Download subtitles"
        required: false
        default: "false"
        type: string

      password:
        description: "Password"
        required: false
        default: ""
        type: string

      user_chat_id:
        description: "Chat ID"
        required: false
        default: ""
        type: string

      bale_gateway_url:
        description: "Gateway URL"
        required: false
        default: ""
        type: string

      user_friendly_quality:
        description: "Quality Label"
        required: false
        default: "Best Quality"
        type: string

      user_friendly_subs:
        description: "Subtitle Label"
        required: false
        default: "Disabled"
        type: string

jobs:
  download:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yt-dlp
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Download Video
        run: |
          yt-dlp "${{ github.event.inputs.youtube_urls }}"
